### ISSUE TITLE
share macro for Notepad++

### ISSUE THREAD

**Issue by floesche** [floesche/R-workshops#13]
Initially we planned to give more examples on how to run pandoc / knitr from a variety of editors. With the support of Makefiles from #12 a large number is supported.
Nevertheless @pistac could share how she runs it from Notepad++...

**Comment by pistac** [comment]
I have added the macro I use (on Windows). This is called "ExportPandoc", it can be found [here](https://github.com/floesche/R-workshops/tree/master/examples).
